"""0001 identity

Revision ID: 7e4a6d55dbbc
Revises:
Create Date: 2026-10-08 23:04:46.205566

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7e4a6d55dbbc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "settings_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text(
                '\'{"run_max_calls": null,"run_max_tokens": null,"run_max_cost_cny": null}\'::jsonb'
            ),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lock_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(settings_json->>'run_max_calls')::int <= 12", name="ck_organizations_run_max_calls"
        ),
        sa.CheckConstraint(
            "(settings_json->>'run_max_tokens')::int <= 60000",
            name="ck_organizations_run_max_tokens",
        ),
        sa.CheckConstraint("slug ~ '^[a-z0-9-]+$'", name="ck_organizations_slug_format"),
        sa.CheckConstraint("slug = lower(slug)", name="ck_organizations_slug_lower"),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_organizations_slug"), "organizations", ["slug"], unique=True, schema="auth"
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("display_name", sa.String(length=50), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "must_change_password", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("failed_login_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lock_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint("role IN ('admin', 'writer', 'reviewer')", name="ck_users_role"),
        sa.CheckConstraint("email = lower(email)", name="ck_users_email_lower"),
        sa.CheckConstraint(
            "failed_login_count >= 0", name="ck_users_failed_login_count_nonnegative"
        ),
        sa.ForeignKeyConstraint(["org_id"], ["auth.organizations.id"], name="fk_users_org"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "email", name="uq_users_org_email"),
        sa.UniqueConstraint("org_id", "id", name="uq_users_org_id_id"),
        schema="auth",
    )
    op.create_index(op.f("ix_auth_users_org_id"), "users", ["org_id"], unique=False, schema="auth")
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now() + interval '12 hours'"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id", "user_id"],
            ["auth.users.org_id", "auth.users.id"],
            name="fk_sessions_user_org",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="uq_sessions_token_hash"),
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_sessions_org_id"), "sessions", ["org_id"], unique=False, schema="auth"
    )
    op.create_index(
        op.f("ix_auth_sessions_user_id"), "sessions", ["user_id"], unique=False, schema="auth"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="sessions", schema="auth")
    op.drop_index(op.f("ix_auth_sessions_org_id"), table_name="sessions", schema="auth")
    op.drop_table("sessions", schema="auth")
    op.drop_index(op.f("ix_auth_users_org_id"), table_name="users", schema="auth")
    op.drop_table("users", schema="auth")
    op.drop_index(op.f("ix_auth_organizations_slug"), table_name="organizations", schema="auth")
    op.drop_table("organizations", schema="auth")
    op.execute("DROP SCHEMA IF NOT EXISTS auth CASCADE")
    # ### end Alembic commands ###
